# Generated by Django 4.2.2 on 2023-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adver', '0003_advers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advers',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='advers',
            name='image',
            field=models.ImageField(default='', upload_to='advers', verbose_name='image'),
            preserve_default=False,
        ),
    ]
