# Generated by Django 4.2.2 on 2023-08-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adver', '0004_rename_updated_at_advers_updated_at_advers_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advers',
            old_name='image',
            new_name='image_of_adv',
        ),
    ]
