# Generated by Django 4.2.2 on 2023-08-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adver', '0005_rename_image_advers_image_of_adv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advers',
            name='image_of_adv',
        ),
    ]
