# Generated by Django 4.2.2 on 2023-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adver', '0006_remove_advers_image_of_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='advers',
            name='image',
            field=models.ImageField(blank=True, upload_to='advers', verbose_name='image'),
        ),
    ]
