# Generated by Django 4.2.2 on 2023-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date_of_create')),
                ('updated_At', models.DateTimeField(auto_now=True, verbose_name='date_of_change')),
                ('is_auction', models.BooleanField(help_text="choose, if it's auction", verbose_name='is_Auction')),
            ],
        ),
    ]
